# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yh8m3LInAc7seBcAsyd-LWKR833yL8Mq
"""

#Este suimbolo se utiliza para comenzqar el codigo.
print("Hola grupo 230 de la carrera tecnica de programacion")
# como consultar el tipo de dato
print( type("soyun dato str")) #tipo ´str´
print(type(5) #tipo ´int´
print(type(1.5)) #tipo ´float´
print(type(3+1j)) #tipo ´complex´
print(type(True)) #tipo bool
print(type("mi cadena de texto")) #tipo ´NoneType´